# Docker Compose file for development purposes.
# Can be used to set up a local instance of Solr.

version: "2"
services:

  solr:
    build:
      context: .
      dockerfile: Dockerfile
    mem_swappinness: 1
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - solr-data:/var/solr

volumes:
  solr-data:
