#!/bin/bash

# Copyright (c) 2006-2024 Apache Software Foundation
# Copyright (c) 2025 MetaBrainz Foundation
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# At first run only, this script starts Solr in SolrCloud mode on localhost,
# uploads the MusicBrainz configsets through API,
# creates the corresponding collections through API too,
# and stops Solr.
# Then, at any run, it starts Solr in SolrCloud mode as normal.
# Any arguments are passed to the final "solr-fg --cloud" command.

set -euo pipefail
echo "Executing $0" "$@"

if [[ "${VERBOSE:-}" == "yes" ]]; then
    set -x
fi

# Could set env-variables for solr-fg
# Install Solr configuration file
source run-initdb

if [[ -f $SOLR_HOME/musicbrainz-solrcloud-first-run ]]; then
    start-local-solrcloud

    create-musicbrainz-collections

    stop-local-solr

    rm "$SOLR_HOME/musicbrainz-solrcloud-first-run"
fi

exec solr-fg --cloud "$@"
